#' Exclusive Economic Zones (EEZs)
#'
#' Polygon data with attributes generated by the Secretariat in 2015 that defines the boundaries of Exclusive Economic Zones in the Convention Area
#'
#' @format A Spatial Polygon Data Frame with 4 rows and 1 variable:
#' \describe{
#'   \item{EEZ_CODE}{the code and label for an EEZ}
#'   ...
#' }
#' @source \url{https://gis.ccamlr.org/home}
"EEZ_data"
