#' Other Fishery Management Areas
#'
#' Polygon data with attributes generated by the Secretariat in 2013 that defines the boundaries of Management Areas in the South Sandwich Islands and South Georgia
#'
#'
#' @format A Spatial Polygon Data Frame with 4 rows and 8 variables:
#' \describe{
#'   \item{Id}{not unique and completely useless}
#'   \item{Areakm2}{probably calculated using gebco 2008 data}
#'   \item{Toothfish}{whether there is toothfish fishing in this area}
#'   \item{Icefish}{whether there is icefish fishing in this area}
#'   \item{MAlabel}{Management area label}
#'   \item{MAname}{Management area full name}
#'   \item{MAcode}{Management area code}
#'   ...
#' }
#' @source \url{https://gis.ccamlr.org/home}
"MA_data"
